name: .NET

on:
  push:
  pull_request:
jobs:
  build:
    runs-on: windows-latest
    name: "Build"
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # SDK Version to use;
        
      - name: Restore
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish '${{ runner.workspace }}/DSMapStudio/src/DSMS/DSMS.csproj' --configuration Release -o deploy

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'DSMS-SHA${{ github.sha }}'
          path: '${{ runner.workspace }}/DSMS/deploy'
>>>>>>> smithbox/main
